 language: node_js
 node_js:
   - "0.10"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/config.travis.json config/config.json
  - npm install -g sequelize@2.0.0-dev10
  - sequelize -m
